export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_IMAGES = "SET_IMAGES";
export const ADD_DETAILS_START = "ADD_DETAILS_START";
export const ADD_DETAILS_SUCCESS = "ADD_DETAILS_SUCCESS";
export const ADD_DETAILS_FAIL = "ADD_DETAILS_FAIL";
export const ADD_DETAILS_SET_SUCCESS = "ADD_DETAILS_SET_SUCCESS";

export const GET_SELLING_PRODUCTS_START = "GET_SELLING_PRODUCTS_START";
export const GET_SELLING_PRODUCTS_SUCCESS = "GET_SELLING_PRODUCTS_SUCCESS";
export const GET_SELLING_PRODUCTS_FAIL = "GET_SELLING_PRODUCTS_FAIL";

export const DELETE_SELLING_ITEM_START = "DELETE_SELLING_ITEM_START";
export const DELETE_SELLING_ITEM_FAIL = "DELETE_SELLING_ITEM_FAIL";
export const DELETE_SELLING_ITEM_SUCCESS = "DELETE_SELLING_ITEM_SUCCESS";

export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
