export const USER_LOADING= 'USER_LOADING';
export const USER_LOADED= 'USER_LOADED';
export const AUTH_ERROR= 'AUTH_ERROR';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAIL= 'LOGIN_FAIL';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS';
export const REGISTER_FAIL= 'REGISTER_FAIL';

export const GET_ERRORS= 'GET_ERRORS';
export const CLEAR_ERRORS= 'CLEAR_ERRORS';

export const SET_IMAGES = "SET_IMAGES";
export const ADD_DETAILS_START = "ADD_DETAILS_START";
export const ADD_DETAILS_SUCCESS = "ADD_DETAILS_SUCCESS";
export const ADD_DETAILS_FAIL = "ADD_DETAILS_FAIL";
export const ADD_DETAILS_SET_SUCCESS = "ADD_DETAILS_SET_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_TOTALS = "ADD_TOTALS";
export const SET_ITEMS = "SET_ITEMS";

export const GET_SELLING_PRODUCTS_START = "GET_SELLING_PRODUCTS_START";
export const GET_SELLING_PRODUCTS_SUCCESS = "GET_SELLING_PRODUCTS_SUCCESS";
export const GET_SELLING_PRODUCTS_FAIL = "GET_SELLING_PRODUCTS_FAIL";
export const GET_ITEM = "GET_ITEM";

export const DELETE_SELLING_ITEM_START = "DELETE_SELLING_ITEM_START";
export const DELETE_SELLING_ITEM_FAIL = "DELETE_SELLING_ITEM_FAIL";
export const DELETE_SELLING_ITEM_SUCCESS = "DELETE_SELLING_ITEM_SUCCESS";

export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_SEARCH_PRODUCTS_START = "GET_SEARCH_PRODUCTS_START";
export const GET_SEARCH_PRODUCTS_SUCCESS = "GET_SEARCH_PRODUCTS_SUCCESS";
export const GET_SEARCH_PRODUCTS_FAIL = "GET_SEARCH_PRODUCTS_FAIL";

export const GET_CHECKOUT_ITEM_START = "GET_CHECKOUT_ITEM_START";
export const GET_CHECKOUT_ITEM_SUCCESS = "GET_CHECKOUT_ITEM_SUCCESS";
export const GET_CHECKOUT_ITEM_FAIL = "GET_CHECKOUT_ITEM_FAIL";
